name: Docker Security Scan

on:
  push:
    branches:
      - main

jobs:
  scan-docker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run Trivy vulnerability scan on backend image
        uses: aquasecurity/trivy-action@0.33.1
        with:
          image-ref: backend:latest
          severity: "CRITICAL,HIGH"

      - name: Run Trivy vulnerability scan on frontend image
        uses: aquasecurity/trivy-action@0.33.1
        with:
          image-ref: frontend:latest
          severity: "CRITICAL,HIGH"
